### ISSUE TITLE
Memory sync issue under multithreaded concurrency

### ISSUE THREAD

**Issue by jamwt** [carllerche/mio#216]
It seems that something along the `notify.rs` and `util/mpmc_bounded_queue.rs` codepath having memory coherence issues under heavy multithreaded loads that utilize `notify()`.

Running the following program in `--release` mode will quickly demonstrate the issue (< 30s on my linux laptop): https://gist.github.com/jamwt/b9df06a87411ea2846aa

Typical Output:

```
$ time cargo run --release
     Running `target/release/mio`
@0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
@100000
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
thread '<main>' panicked at '[BUG] at this point there should always be a message', ../src/libcore/option.rs:330
An unknown error occurred

To learn more, run the command again with --verbose.

real	0m3.473s
user	0m0.320s
sys	0m5.940s

```

**Comment by jamwt** [comment]
Apologies for code quality on the reproduction; had to play around a bit with making threads busy in various ways, and not everything got cleaned up.  It works, though.

**Comment by jamwt** [comment]
Environmental information:

```
$ cat /etc/issue
Debian GNU/Linux jessie/sid \n \l

$ uname -a
Linux tango 3.10-3-amd64 #1 SMP Debian 3.10.11-1 (2013-09-10) x86_64 GNU/Linux

$ rustc --version
rustc 1.3.0-nightly (2671e8cee 2015-06-28)

$ git show | head
commit 27830b901d14682ff77d5a4c487720bb7dbc28e6
Author: Carl Lerche <me@carllerche.com>
Date:   Mon Jul 20 12:22:53 2015 -0700

    Add a link to an MIO blog post

diff --git a/README.md b/README.md
index 5c160af..474615c 100644
--- a/README.md
+++ b/README.md
```

**Comment by jamwt** [comment]
Another note: this was a VM with 4 cores.  Also reproduced on bare metal with 32 cores.  You will most likely need to be on a multicore machine to reproduce.

**Comment by Hoverbear** [comment]
Confirmed on my Arch hardware:

```
hoverbear  ~  git  mio-bug  time cargo run --release
   Compiling libc v0.1.8
   Compiling bytes v0.2.10
   Compiling winapi v0.2.1
   Compiling bitflags v0.1.1
   Compiling winapi-build v0.1.0
   Compiling slab v0.1.1
   Compiling log v0.3.1
   Compiling clock_ticks v0.0.5
   Compiling nix v0.3.9
   Compiling winapi v0.1.23
   Compiling kernel32-sys v0.1.3
   Compiling time v0.1.31
   Compiling syncbox v0.2.3
   Compiling mio v0.4.0 (https://github.com/carllerche/mio#27830b90)
   Compiling eventual v0.1.3
   Compiling mio-bug v0.1.0 (file:///home/hoverbear/git/mio-bug)
     Running `target/release/mio-bug`
@0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
@100000
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
@200000
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
@300000
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
@400000
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
the sum is 0
thread '<main>' panicked at '[BUG] at this point there should always be a message', ../src/libcore/option.rs:330
An unknown error occurred

To learn more, run the command again with --verbose.
cargo run --release  50.66s user 3.76s system 177% cpu 30.579 total
```

**Comment by jamwt** [comment]
Yeah, it's overflowing the integer, so on a non-release built, the bounds checks will fire.

**Comment by jamwt** [comment]
The thread loop + sum print are there as a lazy attempt to generate some work that will not optimize away.

**Comment by jamwt** [comment]
Okay, I think I figured it out.  Short answer: this is not a safe expectation.

PR incoming.

**Comment by Hoverbear** [comment]
@jamwt Wow, awesome!
