### ISSUE TITLE
`EventLoop::register` fails on tcp test on Windows.

### ISSUE THREAD

**Issue by dpc** [carllerche/mio#367]
Mioco got Windows support, yet one simple test keeps failing:

https://github.com/dpc/mioco/blob/ce546a31ea1ec747d606c425fbee0274dd1678b0/src/tests.rs#L994

```
--- tests::tcp_basic_client_server stdout ----
	thread 'tests::tcp_basic_client_server' panicked at 'register failed: Error { repr: Os { code: 10022, message: "An invalid argument was supplied." } }', ../src/libcore\result.rs:746
stack backtrace:
   0:     0x7ff6513b4917 - rt::lang_start::h4a2e63e39ef79a35zKz
   1:     0x7ff6513b40bd - rt::lang_start::h4a2e63e39ef79a35zKz
   2:     0x7ff6513a440f - sys_common::unwind::begin_unwind_inner::h31826283e15e379aqRt
   3:     0x7ff6513a4b1d - sys_common::unwind::begin_unwind_fmt::h063edd6e32820d73wQt
   4:     0x7ff6513af9b2 - rust_begin_unwind
   5:     0x7ff6513b99e8 - panicking::panic_fmt::h365094a389784d78lcM
   6:     0x7ff651358ac3 - unwrap_failed<std::io::error::Error>
                        at C:\projects\src\libcore\macros.rs:29
   7:     0x7ff6510db039 - expect
                        at C:\projects\src\libcore\result.rs:708
   8:     0x7ff6510daf93 - register
                        at C:\projects\mioco\src\evented.rs:269
   9:     0x7ff6510daca5 - register
                        at C:\projects\mioco\src\evented.rs:395
  10:     0x7ff6510ca17f - register_all
                        at C:\projects\mioco\src\coroutine.rs:413
  11:     0x7ff6510c96fb - after_resume
                        at C:\projects\mioco\src\lib.rs:542
  12:     0x7ff6510c7116 - resume
                        at C:\projects\mioco\src\lib.rs:531
  13:     0x7ff6510c6b9a - ready
                        at C:\projects\mioco\src\lib.rs:467
  14:     0x7ff6510e9247 - ready
                        at C:\projects\mioco\src\thread.rs:270
  15:     0x7ff65110974e - io_event
                        at C:\Users\appveyor\.cargo\registry\src\github.com-88ac128001ac3a9a\mio-0.5.0\src\event_loop.rs:343
  16:     0x7ff65110968d - io_process
                        at C:\Users\appveyor\.cargo\registry\src\github.com-88ac128001ac3a9a\mio-0.5.0\src\event_loop.rs:335
  17:     0x7ff6511087d4 - run_once
                        at C:\Users\appveyor\.cargo\registry\src\github.com-88ac128001ac3a9a\mio-0.5.0\src\event_loop.rs:298
  18:     0x7ff6511080c5 - run
                        at C:\Users\appveyor\.cargo\registry\src\github.com-88ac128001ac3a9a\mio-0.5.0\src\event_loop.rs:247
  19:     0x7ff65127c90a - thread_loop<closure>
                        at C:\projects\mioco\src\lib.rs:737
  20:     0x7ff65127a119 - start<closure>
                        at C:\projects\mioco\src\lib.rs:695
  21:     0x7ff6512793c4 - start_threads<closure>
                        at C:\projects\mioco\src\lib.rs:878
  22:     0x7ff65127906a - tcp_basic_client_server
                        at C:\projects\mioco\src\tests.rs:1001
  23:     0x7ff651382142 - stats::Summary::new::h142e9c1c93c7d191qka
  24:     0x7ff651384e17 - stats::Summary::new::h142e9c1c93c7d191qka
  25:     0x7ff6513af918 - sys_common::thread_local::StaticKey::lazy_init::hd3414751e5183916xHt
  26:     0x7ff6513adc02 - sys_common::unwind::inner_try::hbb6eeb03fb5ae63dsOt
  27:     0x7ff6513851c2 - stats::Summary::new::h142e9c1c93c7d191qka
  28:     0x7ff6513b28eb - sys::rand::OsRng.Drop::drop::hc36c2d1e92f70d97CTy
  29:     0x7ffe4dd513d1 - BaseThreadInitThunk
 
 
failures:
    tests::tcp_basic_client_server
 
test result: FAILED. 42 passed; 1 failed; 0 ignored; 0 measured
 
 
Command exited with code 101
```

As I don't have a Windows machine and developing through App Veyor is painfully slow, that's as much as I was able to dig in right now.

**Comment by rrichardson** [comment]
Need to figure out why associate() is being called multiple times,  I don't have a windows box either, but I guess we could start by tracing that method.

**Comment by carllerche** [comment]
Is this still happening? I believe a bunch of windows bugs have been fixed since this issue was created?

**Comment by carllerche** [comment]
I'm closing for now. If the issue still happens, please re-open w/ a repro.
