### ISSUE TITLE
failures on FreeBSD/ARM64

### ISSUE THREAD

**Issue by Licenser** [carllerche/mio#726]
Yap it's esoteric and not part of the list of supported OS's, sorry.

mio's test fails with the following output:
```
[root@thunderx ~/mio]# cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/mio-4b384692d2068fd7

running 5 tests
test event_imp::test_debug_pollopt ... ok
test event_imp::test_debug_ready ... ok
test sys::unix::kqueue::test_coalesce_aio ... ok
test poll::as_raw_fd ... FAILED
test sys::unix::kqueue::does_not_register_rw ... FAILED

failures:

---- poll::as_raw_fd stdout ----
	thread 'poll::as_raw_fd' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `16384`)', src/sys/unix/kqueue.rs:117
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- sys::unix::kqueue::does_not_register_rw stdout ----
	thread 'sys::unix::kqueue::does_not_register_rw' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `16384`)', src/sys/unix/kqueue.rs:117


failures:
    poll::as_raw_fd
    sys::unix::kqueue::does_not_register_rw

test result: FAILED. 3 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

I'm happy to help fix them but some pointeres where to start looking would be super helpful as I don't know the inner workings of mio (yet?)

**Comment by Licenser** [comment]
This seems to be a generic FreeBSD12 issue: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221378 closing it as it seems to be resolved by fixed.
